services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-certificafacil}
      - DB_USER=${DB_USER:-certificafacil}
      - DB_PASS=$SERVICE_PASSWORD_DB
      - APP_URL=${SERVICE_FQDN_APP:-https://certificafacil.qwertyatlas.online}
      - PUBLIC_KEY=${PUBLIC_KEY:-}
      - ACCESS_TOKEN=${ACCESS_TOKEN:-}
      - MP_WEBHOOK_SECRET=${MP_WEBHOOK_SECRET:-}
    volumes:
      - uploads_data:/var/www/html/uploads
      - assets_templates:/var/www/html/assets/templates
      - assets_fonts:/var/www/html/assets/fonts
      - assets_images:/var/www/html/assets/images
      - assets_configs:/var/www/html/assets/configs
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    exclude_from_hc: true
    environment:
      MYSQL_ROOT_PASSWORD: $SERVICE_PASSWORD_DBROOT
      MYSQL_DATABASE: ${DB_NAME:-certificafacil}
      MYSQL_USER: ${DB_USER:-certificafacil}
      MYSQL_PASSWORD: $SERVICE_PASSWORD_DB
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  db_data:
  uploads_data:
  assets_templates:
  assets_fonts:
  assets_images:
  assets_configs:
